/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Matthew-David (https://sketchfab.com/Matthew-David)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-recon-drone-ff2ede3b4ffe42d4afe7c42470c20c05
Title: Sci-Fi Recon Drone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CharacterModel(props) {
  const { nodes, materials } = useGLTF('./drone/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.0007}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
