/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sirsaugsage (https://sketchfab.com/sirsausage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
Title: Fantasy Game Inn
*/

import * as THREE from 'three';
import { RigidBody } from "@react-three/rapier"; 
import { useGLTF, Environment, Sky } from "@react-three/drei";

import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { useMemo } from 'react';
import { useControls } from 'leva';

export default function Map({ position = [0, 0, 0] }) {
const sceneModel = useGLTF("./meeting_space.glb"); 
sceneModel.scene.children.forEach((mesh) => {
    mesh.receiveShadow = true;
    mesh.castShadow = true;
});

  return (
    <group position={position}>
            <RigidBody
                type="fixed"
                colliders="trimesh"
                rotation={[pA.x, pA.y, pA.z]}
                position={[pB.x, -5, pB.z]}
                restitution={0.2}
                friction={0}
            >
                <primitive object={sceneModel.scene} scale={0.8} />
            </RigidBody>
        </group>
  )
}

useGLTF.preload('./meeting_space.glb')
